# Generated by Django 5.2.12 on 2026-04-08 11:18

import apps.common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='audio/%Y/%m/%d/', validators=[apps.common.validators.validate_audio_extension])),
                ('original_filename', models.CharField(max_length=255)),
                ('patient_reference', models.CharField(blank=True, max_length=64)),
                ('encounter_reference', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('audio_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='notes.audiorecording')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('soap', 'SOAP'), ('summary', 'Summary')], default='soap', max_length=32)),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('structured_content', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='notes.transcriptionjob')),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_index', models.PositiveIntegerField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('speaker', models.CharField(blank=True, max_length=64)),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='notes.transcriptionjob')),
            ],
            options={
                'ordering': ('segment_index',),
                'unique_together': {('job', 'segment_index')},
            },
        ),
    ]
